apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-a
  namespace: demos
spec:
  replicas: 3
  selector:
    matchLabels:
      app-zone: demo-a
  template:
    metadata:
      labels:
        app: demo
        app-zone: demo-a
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: us-central1-a
      containers:
      - command:
        - /hello
        - --tag=cluster-2-zone-a
        imagePullPolicy: Always
        image: gcr.io/jeremyot-exp/hello
        name: hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-b
  namespace: demos
spec:
  replicas: 3
  selector:
    matchLabels:
      app-zone: demo-b
  template:
    metadata:
      labels:
        app: demo
        app-zone: demo-b
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: us-central1-b
      containers:
      - command:
        - /hello
        - --tag=cluster-2-zone-b
        imagePullPolicy: Always
        image: gcr.io/jeremyot-exp/hello
        name: hello
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: demos
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: demo
  type: ClusterIP
  topologyKeys:
    - topology.kubernetes.io/zone

